[package]
name = 'vcdreader'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'vcdreader'

[dependencies]
extendr-api = { version = "*", default-features = false, features= ["result_condition"] }
vcd = "0.7.0"
