# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_vcdreader_wrappers", use_symbols = TRUE, package_name = "vcdreader")

#' @usage NULL
#' @useDynLib vcdreader, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Read a VCD file to a DataFrame
#' @export
vcd_reader <- function(file) .Call(wrap__vcd_reader, file)


# nolint end
